package com.example.javaspringboot.Security.Response;

public enum EnumResult {

  EMAIL_REQUIREMENTS_NOT_MET,
  PASSWORD_REQUIREMENTS_NOT_MET,
  CREDENTIALS_EXIST,
  DATE_OF_BIRTH_REQUIREMENTS_NOT_MET,
  TERMS_REQUIREMENTS_NOT_MET,
  UNKNOWN,
  NOT_LOGGED_IN,

  LOGOUT,

  NONE,
  ACCEPTED,
  DISABLED,
  NOT_FOUND,
}
