package com.example.javaspringboot.Utility.Response;

public enum EnumResult {

  EMAIL_REQUIREMENTS_NOT_MET,
  PASSWORD_REQUIREMENTS_NOT_MET,
  CREDENTIALS_EXIST,
  CREDENTIALS_EXPIRED,
  DATE_OF_BIRTH_REQUIREMENTS_NOT_MET,
  TERMS_REQUIREMENTS_NOT_MET,
  UNKNOWN,
  NO_ID_PASSED,
  NOT_LOGGED_IN,
  DUPLICATE,
  LOGOUT,
  DELETED,

  NONE,
  ACCEPTED,
  DISABLED,
  NOT_FOUND,
  ERROR,
  ALREADY_EXISTS,
  DOES_NOT_EXIST,
  UNDETERMINED,
  REMOVE,
  INVALID_UUID,
  BAD_REQUEST
}
